### ISSUE TITLE
Error: Link not found

### ISSUE THREAD

**Issue by jaymin009** [iamatulsingh/instaDataScrap#2]
I have implemented code in local and configured as per provided requirements.
URL: http://localhost:8888/instaDataScrap-master/api.php?u=shre$%$%

Its return me this error
Error: Link not found

**Comment by iamatulsingh** [comment]
can you check if 'shre$%$%' exists on Instagram? 
https://www.instagram.com/shre$%$%

**Comment by iamatulsingh** [comment]
> I have implemented code in local and configured as per provided requirements.
> URL: http://localhost:8888/instaDataScrap-master/api.php?u=shre$%$%
> 
> Its return me this error
> Error: Link not found

can you check if 'shre$%$%' exists on Instagram?
https://www.instagram.com/shre$%$%

If username is not exist on Instagram it will show you that error.

**Comment by jaymin009** [comment]
username is exist. I have not mentioned right username in this comment example.

**Comment by iamatulsingh** [comment]
i'll check this issue. In the meantime can you debug the issue and let me know if you find anything?

**Comment by iamatulsingh** [comment]
> username is exist. I have not mentioned right username in this comment example.

i'll check this issue. In the meantime can you debug the issue and let me know if you find anything?

**Comment by jaymin009** [comment]
I found issue here:
if(($hashtagData = file_get_contents('https://www.instagram.com/explore/tags/' . $hashtag . '/?__a=1', true, $context)) == false){
			echo "Error: Link not found";
			exit;
		}

**Comment by iamatulsingh** [comment]
> I found issue here:
> if(($hashtagData = file_get_contents('https://www.instagram.com/explore/tags/' . $hashtag . '/?__a=1', true, $context)) == false){
> echo "Error: Link not found";
> exit;
> }

can you share username with me? because its working fine for me.

**Comment by jaymin009** [comment]
jaymin_09
This is my username

**Comment by jaymin009** [comment]
Here i have attached screen shot for reference.

**Comment by iamatulsingh** [comment]
> jaymin_09
> This is my username

you can delete your instagram username now. i'll test it.

**Comment by iamatulsingh** [comment]
I found the issue. I'm calling official api to get hash tag values for input username. I've updated the code

**Comment by jaymin009** [comment]
Can you send email address to in response

**Comment by iamatulsingh** [comment]
atulsingh0401@gmail.com

**Comment by jaymin009** [comment]
I am saying instagram object response bro!

In this :
{ "userDetails": { "img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/ecc28812c223eddbe92b483adf9a5646\/5E0969A6\/t51.2885-19\/s150x150\/22636997_138489123546372_7270138481068736512_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net", "full_name": "Jaymin Limbachiya", "username": "jaymin_09", "is_verified": "false", "id": "970381662", "instaUrl": "https:\/\/instagram.com\/jaymin_09" }, "accountDetails": { "followers": "229 Followers", "follow": "493 Following", "posts": "26 Posts" }, "timeLineData": { "data": [ { "post_img": "https:\/\/instagram.famd1-2.fna.fbcdn.net\/vp\/5b0672322c4c977f4d92b760b2d0f1f5\/5DF43194\/t51.2885-15\/e35\/69354657_2179990602109255_633874492552992112_n.jpg?_nc_ht=instagram.famd1-2.fna.fbcdn.net&_nc_cat=107", "post_txt": "Warm welcome @HOME ,\ud83d\udc90\ud83c\udf82", "post_time": "2019-09-02 05:48:47", "post_likes": 32, "post_comments": 1 }, { "post_img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/d6ec7a7e8d0511ed48eb42c788af61c2\/5E0FDE60\/t51.2885-15\/e35\/70413892_139296320649623_8003168119028282586_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net&_nc_cat=111", "post_txt": "#development GO ahead", "post_time": "2019-08-29 09:29:19", "post_likes": 20, "post_comments": 0 }, { "post_img": "https:\/\/instagram.famd1-2.fna.fbcdn.net\/vp\/2c63df87e3893cf2f3ba5034fbe328b6\/5DF95B9A\/t51.2885-15\/e35\/51585965_599463927194244_1437697909515684040_n.jpg?_nc_ht=instagram.famd1-2.fna.fbcdn.net&_nc_cat=100", "post_txt": "#mangala #arti", "post_time": "2019-03-05 06:48:36", "post_likes": 28, "post_comments": 0 }, { "post_img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/452d11a9e97a1c13e619a24e49aa7299\/5E12D42D\/t51.2885-15\/e35\/51797073_875543746131250_8105376002058497472_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net&_nc_cat=110", "post_txt": null, "post_time": "2019-03-04 20:31:16", "post_likes": 19, "post_comments": 0 }, { "post_img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/6e1772a753bdf7796abedb4bc8eebf18\/5D7B3DBB\/t51.2885-15\/e35\/52344417_299308587450230_701218981993065972_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net&_nc_cat=102", "post_txt": "#shiv #ratri", "post_time": "2019-03-04 08:47:01", "post_likes": 10, "post_comments": 1 }, { "post_img": "https:\/\/instagram.famd1-2.fna.fbcdn.net\/vp\/6bfdbf88affcee27789cf92caed9136e\/5DF5C43E\/t51.2885-15\/e35\/42797424_555268894887025_8871033889390606509_n.jpg?_nc_ht=instagram.famd1-2.fna.fbcdn.net&_nc_cat=101", "post_txt": "@office", "post_time": "2018-11-06 16:22:51", "post_likes": 46, "post_comments": 0 }, { "post_img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/8d371ad43d15947b3c8c14447c0271dd\/5D7B08A0\/t51.2885-15\/e35\/43778554_2176189162639618_3563141099547559396_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net&_nc_cat=110", "post_txt": "#", "post_time": "2018-10-28 14:05:09", "post_likes": 20, "post_comments": 4 }, { "post_img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/4f503015c4afbd43b3324457430b436b\/5E04B297\/t51.2885-15\/e35\/27573749_344224522729571_5161426877239263232_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net&_nc_cat=111", "post_txt": "Happy shiv ratri", "post_time": "2018-02-13 14:35:56", "post_likes": 43, "post_comments": 2 }, { "post_img": "https:\/\/instagram.famd1-2.fna.fbcdn.net\/vp\/4481ec2982fcfa4fc871c8396fbc72b1\/5E03BDD1\/t51.2885-15\/e35\/27877810_145562642803812_6791463349432352768_n.jpg?_nc_ht=instagram.famd1-2.fna.fbcdn.net&_nc_cat=100", "post_txt": null, "post_time": "2018-02-11 05:41:44", "post_likes": 31, "post_comments": 1 }, { "post_img": "https:\/\/instagram.famd1-1.fna.fbcdn.net\/vp\/7abeb4b6ccf30b6851b8bfc520ccfc14\/5E1690DB\/t51.2885-15\/e35\/26867760_758658027662194_4163974916640604160_n.jpg?_nc_ht=instagram.famd1-1.fna.fbcdn.net&_nc_cat=110", "post_txt": "#refresh #garden #photogyaphy #memory", "post_time": "2018-02-02 16:32:47", "post_likes": 61, "post_comments": 1 }, { "post_img": "https:\/\/instagram.famd1-2.fna.fbcdn.net\/vp\/2676966572f2455dae4c22accf14e17f\/5E086D03\/t51.2885-15\/e35\/26153739_1233478240087169_166891945107390464_n.jpg?_nc_ht=instagram.famd1-2.fna.fbcdn.net&_nc_cat=105", "post_txt": "Kite festival", "post_time": "2018-01-13 15:49:55", "post_likes": 38, "post_comments": 0 }, { "post_img": "https:\/\/instagram.famd1-2.fna.fbcdn.net\/vp\/efd1e21f0e2a7544c19da2943c19b16f\/5DF14881\/t51.2885-15\/e35\/23507035_166414723951938_5514359161883721728_n.jpg?_nc_ht=instagram.famd1-2.fna.fbcdn.net&_nc_cat=106", "post_txt": "#jay #limbach", "post_time": "2017-11-11 17:02:28", "post_likes": 33, "post_comments": 1 } ], "count": 12 } }

**Comment by iamatulsingh** [comment]
You won't get email id because that's not public.

**Comment by iamatulsingh** [comment]
I'm closing this issue. Please reopen the issue if you face it again.
