### ISSUE TITLE
Issue Error

### ISSUE THREAD

**Issue by winbotscript** [iamatulsingh/instaDataScrap#3]
Hi there,

I found this issue 

Notice: Undefined offset: 1 in /home/xxxxx/domain.com/api/instagram.php on line 124

Notice: Undefined offset: 2 in /home/xxxxx/domain.com/api/instagram.php on line 125

I use subdomain, help me please to resolved this an issue

**Comment by iamatulsingh** [comment]
Please provide more details. What's your domain ? Are you using proper URL
or not?

**Comment by winbotscript** [comment]
here the link https://api.sakarepmu.online/instagram.php?u=jokowi&hashtag=jokowi

**Comment by iamatulsingh** [comment]
Which file are you using and have you made any changes to code? Please put
screenshot here at line number 124-125 from your code if you made any
changes.

**Comment by iamatulsingh** [comment]
I'm closing this issue since past 27 days their are no response.
