### ISSUE TITLE
Not work in production

### ISSUE THREAD

**Issue by karrarjasim** [iamatulsingh/instaDataScrap#5]
It's work in local only .
this response return when run  script to server 
`{ "userDetails": { "img": null, "full_name": null, "username": null, "is_verified": "false", "id": null, "instaUrl": "https:\/\/instagram.com\/" }, "accountDetails": { "followers": "", "follow": null, "posts": "" }, "timeLineData": { "data": [], "count": 0 }, "hashTagLikes": null, "tagData": null } `

**Comment by iamatulsingh** [comment]
I don't know the exact issue but possibility is your cloud server IP is black listed on instagram sides.
Anyways if you debug something and tell that will be better. I'll check once I'm free.

**Comment by iamatulsingh** [comment]
Many people used this one there server and its working for them. Couls you please check the issue from your side and tell me?

**Comment by iamatulsingh** [comment]
No response from past 1 month so closing this issue. Please reopen if still having same issue.
